sudo_nopasswd: no

# users description  
users:  
  underpass: #default user
    password: '$6$PCHTU4lEg/AuAXXi$gcNIABobANSTN9V6IWTFwrVNE7FACwIh5MFl7W4Af/FlsZNZbMP6vgO264f.yFzm1J4rgjVV6NulZQFlyL5l31'
    shell: /bin/bash
  underpass2:
    password: '$6$KaosNQg.tjbbWTVf$6pwFYsKUNRGKbjvbkytqTlqrR.d6Fnh7s7cXNq2eEYyjOGcDctMHFaLyV3iXPvi1j.MxgZSajy73ebVKxr27W/'
    shell: /bin/false