sudo_nopasswd: no

# list of users
# SSH password can be generated online @ https://www.mkpasswd.net/?type=crypt-sha512
# or via command line: mkpasswd -m sha-512 'my_password'

users:  
  # default user
  underpass:
    password: '$6$G0AxXlTW1MEq/.kc$5BA0YJ.AOmSOEviUPuKlIcc8R5ur5.nEPgUlAZJSTku4PkwBQRVZJgkBprgVQLZu8d8MTPPSwl/kUEpmNcQQ7/'
    shell: /bin/false

  user2:
    password: '$6$QWnP50MDsD9Rg1.q$YWht713.AOCu4SLT5sh.m1a2ou2YFGP/Sp/Ig5rPFW36/gpPmR68pKV0d5Oifwjh3Tu8YwqTXBTXb1zcbW4XZ0'
    shell: /bin/false
  
