version: '3'

networks:
    underpass:

volumes:
    ovpn_data: {}

services:
    openvpn:
        image: kylemanna/openvpn
        container_name: openvpn
        restart: always
        cap_add:
            - NET_ADMIN
        networks:
            - underpass
        ports:
            - "$OPENVPN:1194/udp"
        volumes: 
            - ovpn_data:/etc/openvpn
    
    stunnel:
        image: