version: '3'

networks:
    underpass:

volumes:
    ovpn_data: {}
    wireguard_config: {}

services:
    openvpn:
        image: kylemanna/openvpn
        container_name: openvpn
        restart: always
        cap_add:
            - NET_ADMIN
        networks:
            - underpass
        ports:
            - "$OPENVPN_UDP:1194/udp"
        volumes: 
            - ovpn_data:/etc/openvpn
    
    stunnel:
        image: vimagick/stunnel
        container_name: stunnel
        restart: always
        networks:
            - underpass
        ports:
            - "$STUNNEL:4911"
        links:
            - openvpn
        environment: 
            - CLIENT=no
            - SERVICES=openvpn
            - ACCEPT=0.0.0.0:4911
            - CONNECT=openvpn:1194
    
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        restart: always
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        networks: 
            - underpass
        ports:
            - "$WIREGUARD:51820/udp"
        environment:
            - TZ=$TZ
            - wireguard_config:config
            - /lib/modules:/lib/modules
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
    
    shadowsocks: