version: '3.3'

networks:
    underpass:
    default:
        driver: bridge

volumes: 
    portainer_data: {}
    droppy_config: {}
    droppy_files: {}
    heimdall_config: {}

services:
    pritunl:
        image: jippi/pritunl:latest
        container_name: pritunl
        restart: always
        privileged: true
        networks: 
            - underpass
        ports:
            - "$PRITUNL_WEB_UI:80"
            - "$PRITUNL_WEB_UI_HTTPS:443"
            - "$PRITUNL_TCP:1194/tcp"
            - "$PRITUNL_TCP:1194/udp"
    
    shadowsocks:
        image: easypi/shadowsocks-libev:latest
        container_name: shadowsocks
        restart: always
        networks: 
            - underpass
        ports:
            - "$SHADOWSOCKS_TCP:8388/tcp"
            - "$SHADOWSOCKS_UDP:8388/udp"
        environment: 
            - METHOD=aes-256-cfb
            - PASSWORD=$SHADOWSOCKS_PASSWORD
    
    squid:
        image: b4tman/squid:latest
        container_name: squid
        restart: always
        networks: 
            - underpass
        ports:
            - "$SQUID_PORT:3128"

    privoxy:
        image: splazit/privoxy-alpine:latest
        container_name: privoxy
        restart: always
        networks: 
            - underpass
        ports:
            - "$PRIVOXY_PORT:8118"
    
    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        networks:
            - underpass
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer_data:/data
        
    droppy:
        image: silverwind/droppy
        container_name: droppy
        restart: unless-stopped
        networks: 
            - underpass
        ports:
            - "$DROPPY_PORT:8989"
        volumes:
            - droppy_config:/config
            - droppy_files:/files
    
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: always
        networks:
            - underpass
        ports:
            - "$HEIMDALL_PORT:80"
            - "$HEIMDALL_PORT_HTTPS:443"
        volumes:
            - heimdall_config:/config

    