version: '3.3'

networks:
    underpass:
    default:
        driver: bridge

services:
    pritunl:
        image: jippi/pritunl
        container_name: pritunl
        restart: always
        privileged: true
        networks: 
            - underpass
        ports:
            - 80:80
            - 443:443
            - "$PRITUNL_TCP:1194/tcp"
            - "$PRITUNL_TCP:1194/udp"
    
    shadowsocks:
        image: easypi/shadowsocks-libev
        container_name: shadowsocks
        restart: always
        networks: 
            - underpass
        ports:
            - "$SHADOWSOCKS_TCP:8388/tcp"
            - "$SHADOWSOCKS_UDP:8388/udp"
        environment: 
            - METHOD=aes-256-cfb
            - PASSWORD=$SHADOWSOCKS_PASSWORD
    

    