version: '3.6'

networks:
    underpass:
        external: true
    
volumes:
    mongodb: {}
    wireguard_config: {}
    portainer_data: {}
    droppy_config: {}
    droppy_files: {}
    heimdall_config: {}
    prometheus_data: {}
    grafana_data: {}

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        networks: 
            - underpass
        volumes: 
            - mongodb:/data/db

    pritunl:
        image: goofball222/pritunl:latest
        container_name: pritunl
        depends_on: 
            - mongodb
        links:
            - mongodb
        restart: always
        privileged: true
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        networks: 
            - underpass
        ports:
            - "$PRITUNL_PORT:80"
            - "$PRITUNL_PORT_HTTPS:443"
            - "$PRITUNL_TCP:1194/tcp"
            - "$PRITUNL_TCP:1194/udp"
            - "$PRITUNL_WIREGUARD:1195/udp"
        environment: 
            - MONGODB_URI=mongodb://mongodb:27017/pritunl
        volumes: 
            - /etc/localtime:/etc/localtime:ro

    wireguard:
        image: linuxserver/wireguard:latest
        container_name: wireguard
        restart: always
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        networks:
            - underpass
        ports:
            - "$WIREGUARD_PORT:51820/udp"
        environment:
            - TZ=$TZ
            - SERVERURL=auto
            - SERVERPORT=$WIREGUARD_PORT
            - PEERS=$WIREGUARD_PEERS
            - PEERDNS=$WIREGUARD_DNS
            - INTERNAL_SUBNET=$WIREGUARD_INTERNAL_IP
        volumes:
            - wireguard_config:/config
            - /lib/modules:/lib/modules
    
    shadowsocks:
        image: easypi/shadowsocks-libev:latest
        container_name: shadowsocks
        restart: always
        networks: 
            - underpass
        ports:
            - "$SHADOWSOCKS_TCP:8388/tcp"
            - "$SHADOWSOCKS_UDP:8388/udp"
        environment: 
            - METHOD=aes-256-cfb
            - PASSWORD=$SHADOWSOCKS_PASSWORD
    
    squid:
        image: b4tman/squid:latest
        container_name: squid
        restart: always
        networks: 
            - underpass
        ports:
            - "$SQUID_PORT:3128"
        environment:
            - SQUID_CONFIG_FILE:/etc/squid/my-squid.conf
        volumes:
            - ./config/squid/squid.conf:/etc/squid/my-squid.conf

    privoxy:
        image: splazit/privoxy-alpine:latest
        container_name: privoxy
        restart: always
        networks: 
            - underpass
        ports:
            - "$PRIVOXY_PORT:8118"
        
    dante:
        image: vimagick/dante
        container_name: dante
        restart: always
        networks:
            - underpass
        ports:
            - "$SOCKS5_PORT:1080"
        volumes:
            - ./config/dante-socks/sockd.conf:/etc/sockd.conf
    
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        networks:
            - underpass
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer_data:/data
        
    droppy:
        image: silverwind/droppy
        container_name: droppy
        restart: unless-stopped
        networks: 
            - underpass
        ports:
            - "$DROPPY_PORT:8989"
        volumes:
            - droppy_config:/config
            - droppy_files:/files
    
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: always
        networks:
            - underpass
        ports:
            - "$HEIMDALL_PORT:80"
            - "$HEIMDALL_PORT_HTTPS:443"
        volumes:
            - heimdall_config:/config

    prometheus:
        image: prom/prometheus:v2.20.1
        container_name: prometheus
        restart: unless-stopped
        networks:
            - underpass
        expose:
            - 9090
        labels:
            org.label-schema.group: "monitoring"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=200h'
            - '--web.enable-lifecycle'
        volumes:
            - ./config/prometheus:/etc/prometheus
            - prometheus_data:/prometheus

    alertmanager:
        image: prom/alertmanager:v0.21.0
        container_name: alertmanager
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - "$ALERTMANAGER_PORT:9093"
        labels:
            org.label-schema.group: "monitoring"
        volumes:
            - ./config/alertmanager:/etc/alertmanager

    nodeexporter:
        image: prom/node-exporter:v1.0.1
        container_name: nodeexporter
        restart: unless-stopped
        networks:
            - underpass
        expose:
            - 9100
        labels:
            org.label-schema.group: "monitoring"
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.37.0
        container_name: cadvisor
        restart: unless-stopped
        networks:
            - underpass
        expose:
            - 8080
        labels:
            org.label-schema.group: "monitoring"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro

    grafana:
        image: grafana/grafana:7.1.5
        container_name: grafana
        restart:
            - unless-stoppped
        networks:
            - underpass
        ports:
            - "$GRAFANA_PORT:3000"
        labels:
            org.label-schema.group: "monitoring"
        environment:
            - GF_SECURITY_ADMIN_USER=$GRAFANA_ADMIN_USER
            - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASS
            - GF_USERS_ALLOW_SIGN_UP=false
        volumes:
            - grafana_data:/var/lib/grafana
            - ./config/grafana/provisioning:/etc/grafana/provisioning

    pushgateway:
        image: prom/pushgateway:v1.2.0
        container_name: pushgateway
        restart: unless-stopped
        networks:
            - underpass
        expose:
            - 9091
        labels:
            org.label-schema.group: "monitoring"

