version: '3.6'

networks:
    underpass:
        external: true
    
volumes:
    mongodb: {}
    wireguard_config: {}
    ssh_config: {}
    dante_config: {}
    portainer_data: {}

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        networks: 
            - underpass
        volumes: 
            - mongodb:/data/db

    pritunl:
        image: goofball222/pritunl:latest
        container_name: pritunl
        depends_on: 
            - mongodb
        links:
            - mongodb
        restart: unless-stopped
        privileged: true
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        networks:
            - underpass
        ports:
            - "$PRITUNL_PORT:80"
            - "$PRITUNL_PORT_HTTPS:443"
            - "$PRITUNL_TCP:1194/tcp"
            - "$PRITUNL_TCP:1194/udp"
        environment: 
            - MONGODB_URI=mongodb://mongodb:27017/pritunl
        volumes: 
            - /etc/localtime:/etc/localtime:ro

    wireguard:
        image: linuxserver/wireguard:latest
        container_name: wireguard
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv6.conf.all.disable_ipv6=0
        networks:
            - underpass
        ports:
            - "$WIREGUARD_PORT:51820/udp"
        environment:
            - TZ=$TZ
            - SERVERURL=auto
            - SERVERPORT=$WIREGUARD_PORT
            - PEERS=$WIREGUARD_PEERS
            - PEERDNS=$WIREGUARD_DNS
            - INTERNAL_SUBNET=$WIREGUARD_INTERNAL_IP
        volumes:
            - wireguard_config:/config
            - /lib/modules:/lib/modules

    shadowsocks:
        image: gists/shadowsocks-libev:latest
        container_name: shadowsocks
        restart: unless-stopped
        networks: 
            - underpass
        ports:
            - "$SHADOWSOCKS_TCP:8388/tcp"
            - "$SHADOWSOCKS_UDP:8388/udp"
        environment: 
            - METHOD=$SHADOWSOCKS_METHOD
            - PASSWORD=$SHADOWSOCKS_PASSWORD
        
    squid:
        image: b4tman/squid:latest
        container_name: squid
        restart: unless-stopped
        network_mode: host
        environment:
            - SQUID_CONFIG_FILE:/etc/squid/squid.conf
        volumes:
            - ./config/squid/squid.conf:/etc/squid/squid.conf
            - ./config/squid/users:/etc/squid/users
        
    dante:
        image: wernight/dante:latest
        container_name: dante
        restart: unless-stopped
        network_mode: host
        volumes:
            - dante_config:/etc
            - ./config/dante/sockd.conf:/etc/sockd.conf
        
    ssh:
        image: yuriyvlasov/openssh-server
        container_name: ssh
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - "$SSH_PORT:22"
        volumes:
            - ssh_config:/etc/sshd
            - ./config/openssh/config.yml:/config.yml

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        command: -H unix:///var/run/docker.sock
        networks:
            - underpass
        ports:
            - "9000:9000"
            - "8000:8000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer_data:/data
        

        