version: '3'

networks:
    underpass:

volumes:
    ovpn_data: {}

services:
    openvpn:
        image: kylemanna/openvpn
        container_name: openvpn
        restart: always
        cap_add:
            - NET_ADMIN
        networks:
            - underpass
        ports:
            - "$OPENVPN_UDP:1194/udp"
        volumes: 
            - ovpn_data:/etc/openvpn
    
    stunnel:
        image: vimagick/stunnel
        container_name: stunnel
        restart: always
        networks:
            - underpass
        ports:
            - "$STUNNEL:4911"
        links:
            - openvpn
        environment: 
            - CLIENT=no
            - SERVICES=openvpn
            - ACCEPT=0.0.0.0:4911
            - CONNECT=openvpn:1194