version: '3.3'

networks:
    underpass:
    default:
        driver: bridge
    
volumes: 
    portainer_data: {}
    projectsend_data: {}
    projectsend_config: {}

services:
    pritunl:
        image: jippi/pritunl:latest
        container_name: pritunl
        restart: always
        privileged: true
        networks: 
            - underpass
        ports:
            - 80:80
            - 443:443
            - "$PRITUNL_TCP:1194/tcp"
            - "$PRITUNL_TCP:1194/udp"
    
    shadowsocks:
        image: easypi/shadowsocks-libev:latest
        container_name: shadowsocks
        restart: always
        networks: 
            - underpass
        ports:
            - "$SHADOWSOCKS_TCP:8388/tcp"
            - "$SHADOWSOCKS_UDP:8388/udp"
        environment: 
            - METHOD=aes-256-cfb
            - PASSWORD=$SHADOWSOCKS_PASSWORD
    
    squid:
        image: b4tman/squid:latest
        container_name: squid
        restart: always
        networks: 
            - underpass
        ports:
            - "$SQUID_PORT:3128"

    privoxy:
        image: splazit/privoxy-alpine:latest
        container_name: privoxy
        restart: always
        networks: 
            - underpass
        ports:
            - "$PRIVOXY_PORT:8118"
    
    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        networks:
            - underpass
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer_data:/data
    
    projectsend:
        image: linuxserver/projectsend:latest
        container_name: projectsend
        restart: unless-stopped
        networks: 
            - underpass
        ports:
            - "$PROJECTSEND:80"
        environment: 
            - MAX_UPLOAD=$MAX_FILE_UPLOAD_SIZE
        volumes: 
            - projectsend_config:/config
            - projectsend_data:/data


    