version: '3.3'

networks:
    underpass:

volumes:
    openvpn-data: {}
    openvpn-db: {}
    wireguard_config: {}
    wireguard_ui: {}

services:
    openvpn:
        image: awalach/openvpn
        container_name: openvpn
        restart: always
        cap_add:
            - NET_ADMIN
        networks:
            - underpass
        ports:
            - "$OPENVPN_UDP:1194/udp"
        volumes: 
            - openvpn-data:/etc/openvpn
        depends_on: 
            - "openvpn-gui"
    
    openvpn-tcp:
        image: awalach/openvpn
        container_name: openvpn-tcp
        restart: always
        cap_add:
            - NET_ADMIN
        networks:
            - underpass
        ports: 
            - "$OPENVPN_TCP:1194/tcp"
        volumes:
            - openvpn-data:/etc/openvpn
        command:
            - ovpn_run --proto tcp
        depends_on: 
            - "openvpn-gui"
    
    openvpn-gui:
        image: awalach/openvpn-web-ui
        container_name: openvpn-gui
        restart: always
        networks: 
            - underpass
        ports: 
            - "$OPENVPN_GUI:8080"
        volumes:
            - openvpn-data:/etc/openvpn
            - openvpn-db:/opt/openvpn-gui/db
    
    stunnel:
        image: vimagick/stunnel
        container_name: stunnel
        restart: always
        networks:
            - underpass
        ports:
            - "$STUNNEL:4911"
        depends_on:
            - openvpn
        environment: 
            - CLIENT=no
            - SERVICES=openvpn
            - ACCEPT=0.0.0.0:4911
            - CONNECT=openvpn:1194
    
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        restart: always
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        networks: 
            - underpass
        ports:
            - "$WIREGUARD:51820/udp"
        environment:
            - TZ=$TZ
            - wireguard_config:config
            - /lib/modules:/lib/modules
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
    
    wireguard-ui:
        image: embarkstudios/wireguard-ui
        container_name: wireguard-ui
        restart: always
        privileged: true
        networks:
            - underpass
        ports:
            - "$WIREGUARD_GUI:8080"
            - "$WIREGUARD:5555"
        volumes:
            - wireguard_ui:/data
        entrypoint:
            - /wireguard-ui
    
    shadowsocks:
        image: easypi/shadowsocks-libev
        container_name: shadowsocks
        restart: always
        networks: 
            - underpass
        ports:
            - "$SHADOWSOCKS:8388/tcp"
            - "$SHADOWSOCKS:8388/udp"
        environment: 
            - METHOD=aes-256-cfb
            - PASSWORD=$SHADOWSOCKS_PASSWORD
    
    dropbear:
        image: sjourdan/alpine-sshd
        container_name: dropbear
        restart: always
        networks: 
            - underpass
        ports:
            - $SSH_PORT:22

    