---
- hosts: control

  become: true

  vars_files:
    - "./ansible/vars/vars.yml"

  roles:
    - geerlingguy.docker

  tasks:
    - include_tasks: ./ansible/playbooks/setup-centos.yml
      when: ansible_distribution == 'CentOS'
    
    - include_tasks: ./ansible/playbooks/setup-ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

    - name: Set Nano Environment
      lineinfile:
        path: ~/.nanorc
        line: "/usr/share/nano/sh.nanorc"
        create: yes

    - name: Add to Bash Profile
      lineinfile:
        path: ~/.bashrc
        insertafter: 'EOF'
        line: "export VISUAL=nano"

    - name: Insert Public IP to Squid Config
      lineinfile:
        path: /opt/underpass/config/squid/squid.conf
        regexp: '^acl SSH dst'
        line: "acl SSH dst {{ ansible_eth0.ipv4.address }}-{{ ansible_eth0.ipv4.address }}/32"

    - name: Ensure Firewalld is Started
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Ensure Docker Daemon is Restarted
      service:
        name: docker
        state: restarted

    - name: Add Squid and Dante SOCKS Default Ports to Firewall
      command: "{{ item }}"
      with_items:
        - "firewall-cmd --zone=public --add-service=squid --permanent"
        - "firewall-cmd --zone=public --add-port=1080/tcp --permanent"
        - "firewall-cmd --reload"
