---
- hosts: control

  become: true

  tasks:
    - include_tasks: ./ansible/playbooks/setup-centos.yml
      when: ansible_distribution == 'CentOS'
    
    - include_tasks: ./ansible/playbooks/setup-ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

    - name: Set Nano Environment
      lineinfile:
        path: ~/.nanorc
        line: "/usr/share/nano/sh.nanorc"
        create: yes

    - name: Add to Bash Profile
      lineinfile:
        path: ~/.bashrc
        insertafter: 'EOF'
        line: "export VISUAL=nano"

    - name: Insert Public IP to Squid Config
      lineinfile:
        path: /opt/underpass/config/squid/squid.conf
        regexp: '^acl SSH dst'
        line: "acl SSH dst {{ ansible_eth0.ipv4.address }}-{{ ansible_eth0.ipv4.address }}/32"

    - name: Ensure Firewalld is Started
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Add Squid Default Port to Firewall
      firewalld:
        zone: public
        service: squid
        permanent: yes
        state: enabled

    - name: Add Dante SOCKS Default Port to Firewall
      firewalld:
        zone: public
        port: 1080/tcp
        permanent: yes
        state: enabled

    - name: Install Underpass
      docker_compose:
        project_src: ./

  vars_files:
    - "./ansible/vars/docker.yml"

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker