---
- hosts: control

  become: true

  vars_files:
    - "./ansible/vars/vars.yml"

  roles:
    - geerlingguy.docker
      tags: [ 'docker-install' ]

  tasks:
    - include_tasks: ./ansible/playbooks/setup-centos.yml
      when: ansible_distribution == 'CentOS'
    
    - include_tasks: ./ansible/playbooks/setup-ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

    - include: ./ansible/playbooks/control.yml
