---
# tasks: (continuation)
    - name: Set Nano Environment
      lineinfile:
        path: ~/.nanorc
        line: "/usr/share/nano/sh.nanorc"
        create: yes

    - name: Add Nano to Bash Profile
      lineinfile:
        path: ~/.bashrc
        insertafter: 'EOF'
        line: "export VISUAL=nano"

    - name: Insert Public IP to Squid Config
      lineinfile:
        path: /opt/underpass/config/squid/squid.conf
        regexp: '^acl SSH dst'
        line: "acl SSH dst {{ ansible_eth0.ipv4.address }}-{{ ansible_eth0.ipv4.address }}/32"

    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted
        enabled: yes

    - name: Sleep for a while
      wait_for:
        delay: 10

    - name: Add Squid and Dante SOCKS Default Ports to Firewall
      command: "{{ item }}"
      with_items:
        - "iptables -F"
        - "firewall-cmd --zone=public --add-service=squid --permanent"
        - "firewall-cmd --zone=public --add-port=1080/tcp --permanent"
        - "firewall-cmd --reload"

    - name: Ensure Docker Daemon is Restarted
      service:
        name: docker
        state: restarted

    - name: Install Underpass
      command: "{{ item }}"
      with_items:
        - "cd /opt/underpass"
        - "docker network create underpass --subnet 172.20.0.0/24"
        - "docker-compose up -d"