---
    - name: Update System
      yum:
        name: *
        state: latest
    
    - name: Install ELRepo
      yum:
        name: elrepo-release
        state: present

    - name: Install Wireguard Kernel Modules
      yum:
        name: ['kmod-wireguard', 'wireguard-tools', 'yum-plugin-elrepo']
        state: present

    - name: Install System Tools
      yum:
        name: ['glances', 'htop', 'nano', 'ncdu', 'net-tools', 'ntp', 'rsync', 'screen', 'wget', 'yum-utils']
        state: present

    - name: Install Fail2Ban
      yum:
        name: fail2ban
        state: present

    - name: Configure Fail2Ban
      copy:
        src: /opt/underpass/config/fail2ban/jail-centos.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '644'

    - name: Start Fail2Ban
      service:
        name: fail2ban
        state: started
        enabled: yes

