version: '3.3'

volumes: 
    mariadb: {}
    phpmyadmin: {}
    nginx-proxy-manager: {}

services:
    mariadb:
        image: linuxserver/mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        networks: 
            - underpass
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - TZ=$TZ
        volumes: 
            - mariadb:/config
        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - "$PHPMYADMIN_PORT:80"
        environment:
            - PMA_ARBITRARY=0
            - PMA_HOST=mariadb
        volumes:
            - phpmyadmin:/sessions

    nginx-proxy-manager:
        image: jlesage/nginx-proxy-manager:latest
        container_name: nginx-proxy-manager
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - 8181:8181
            - 8080:8080
            - 4443:4443
        volumes:
            - nginx-proxy-manager:/config
