version: '3.3'

services:
    rdesktop:
        image: linuxserver/rdesktop
        container_name: rdesktop
        restart: unless-stopped
        privileged: true
        networks:
            - underpass
        ports:
            - "$RDESKTOP_PORT:3389"
        shm_size: "1gb"
        
